# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartnerName', models.CharField(max_length=20)),
                ('PartnerAddress', models.CharField(max_length=100)),
                ('PartnerTransmitFreq', models.IntegerField()),
                ('PartnerOAUTHTOken', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RandomBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canary', models.CharField(max_length=6)),
                ('DataBlock', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='SensorDataBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorName', models.CharField(max_length=10)),
                ('SensorDescriptor', models.CharField(max_length=20)),
                ('SensorValue', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdateVersion', models.CharField(max_length=20)),
                ('UpdatePath', models.CharField(max_length=100)),
            ],
        ),
    ]
